# filepaths
SOME_FOLDER: data/test-clean

# checkpoints
exp_folder: 
use_greedy: true

# trivials
batch_size: 
num_workers: 

# loading options
run_all: true

# IF NOT run all
epoch_num: 
# make sure it exists under ckpts/ folder

# whether to load averages
run_avg: false