# filepaths
# ------------------------------------------------
TRN_FOLDER: data/train-clean-100
DEV_FOLDER: data/dev-clean
TST_FOLDER: data/test-clean
EXP_FOLDER: experiments

# training
# ------------------------------------------------
seed: 11785
epochs: 60
batch_size: 128
num_workers: 15
accu_grad: 6
grad_norm: 10.0
eval_ld_interval: 4
init_force: true
tf_rate: 1.0
max_savings: 3
use_specaug: true

# wandb
# ------------------------------------------------
wandb:
  use: true
  configs:
    project: hw4-full
    reinit: true
    entity: Astromsoc

# configurations to train the model
# ------------------------------------------------
model:
  tag: base-LAS
  configs:
    listener_configs:
      input_dim: 15
      uniform_hid_dim: 512
      lstm_layers: 1
      plstm_layers: 3
      bidirectional: true
      init_dropout: 0.2
      mid_dropout: 0.25
      final_dropout: 0.3
    speller_configs:
      # encoder + attention
      att_proj_dim: 256
      att_heads: 1
      att_dropout: 0.3
      # decoder embeddings
      dec_emb_dim: 512
      dec_emb_dropout: 0.4
      # decoder lstm cells
      dec_lstm_hid_dim: 512
      dec_lstm_out_dim: 256
      dec_lstm_dropout: 0.3
      # trivials
      CHR_MAX_STEPS: 600
      USE_GREEDY: true

# optimizer
optimizer:
  name: adamw
  configs:
    lr: 0.001
    weight_decay: 5.0e-6
    amsgrad: true

# scalar
scaler:
  use: true

# batch scheduler
batch_scheduler:
  use: false
  configs:
    warmup_epochs: 0.5

# epoch scheduler
epoch_scheduler:
  use: true

# tf rate scheduler
tf_rate_scheduler:
  use: true
  configs:
    factor: 0.015

# dropout scheduler
dropout_scheduler:
  use: true
  configs:
    0: 0.2
    5: 4
    20: 1.25
    40: 0.5

# criterion: fixed to CrossEntropyLoss(reduction='none')